name: Docs Build Deploy Workflow
on:
  push:
    branches:
      - master
jobs:
  build_test_and_publish:
    name: Build and Test the Application
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required for gh-pages deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js using 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - name: Configure Git
        run: |
          git config --local user.email "sysadmin@binary.com"
          git config --local user.name "gh-pages deploy bot"
      - name: Install Packages
        run: npm install
      - name: Deploy to gh-pages
        run: npm run gh-pages
